--------------------------------------------------------------------------------
-- KMLeon :: smoke test
--------------------------------------------------------------------------------
-- Builds a small job (point via GeoJSON, line via SDO, polygon via GeoJSON),
-- runs it synchronously as KML, and prints the result. Run after install.sql.
-- Uses KML output to avoid the APEX_ZIP dependency. Requires SDO_UTIL.
--------------------------------------------------------------------------------
set serveroutput on size unlimited
set lines 200

declare
  l_job number;
  l_a   number;
  l_kml clob;
begin
  l_job := pck_kml_job_api.create_job(
             p_document_name => 'KMLeon smoke test',
             p_description   => 'Generated by tests/smoke_test.sql',
             p_output_format => 'KML',
             p_user_tab      => 'DEMO_USERS',
             p_user_id       => '42');

  -- styled point, with variable metadata, geometry as GeoJSON
  l_a := pck_kml_job_api.add_asset(
           p_job_id           => l_job,
           p_geometry_geojson => to_clob('{"type":"Point","coordinates":[13.4050,52.5200]}'),
           p_name             => 'Berlin',
           p_folder_name      => 'Cities',
           p_icon_scale       => 1.2,
           p_label_color      => pck_kml_engine.rgba_to_kml('FFFFFF'),
           p_extended_data    => to_clob('{"country":"DE","population":"3677000"}'));

  -- line, geometry as native SDO_GEOMETRY (2002 = line, SRID 4326)
  l_a := pck_kml_job_api.add_asset(
           p_job_id       => l_job,
           p_geometry_sdo => sdo_geometry(
                               2002, 4326, null,
                               sdo_elem_info_array(1, 2, 1),
                               sdo_ordinate_array(13.40,52.52, 11.58,48.14, 8.68,50.11)),
           p_name         => 'Route',
           p_folder_name  => 'Routes',
           p_line_color   => pck_kml_engine.rgba_to_kml('FF0000'),   -- red
           p_line_width   => 3);

  -- filled polygon, geometry as GeoJSON
  l_a := pck_kml_job_api.add_asset(
           p_job_id           => l_job,
           p_geometry_geojson => to_clob('{"type":"Polygon","coordinates":'
                                || '[[[13.3,52.4],[13.5,52.4],[13.5,52.6],[13.3,52.6],[13.3,52.4]]]}'),
           p_name             => 'Area',
           p_folder_name      => 'Areas',
           p_line_color       => pck_kml_engine.rgba_to_kml('0000FF'),
           p_poly_color       => pck_kml_engine.rgba_to_kml('0000FF', 80),
           p_poly_fill        => 'Y');

  commit;
  pck_kml_job_api.run_now(l_job);

  dbms_output.put_line('status      : ' || pck_kml_job_api.get_status(l_job));
  l_kml := pck_kml_job_api.get_kml(l_job);
  dbms_output.put_line('kml length  : ' || nvl(dbms_lob.getlength(l_kml), 0));
  dbms_output.put_line('--------------------------------------------------');
  dbms_output.put_line(dbms_lob.substr(l_kml, 3900, 1));
end;
/
