--------------------------------------------------------------------------------
-- KMLeon :: table KML_JOB_ASSETS
--------------------------------------------------------------------------------
-- One row per map feature of a job. Geometry is supplied as SDO_GEOMETRY OR as
-- GeoJSON (separate columns); the engine converts via SDO_UTIL. Variable
-- metadata (name + arbitrary properties) is surfaced in the KML.
-- All DML goes through PCK_KML_JOB_ASSETS_DML; never write this table directly.
--------------------------------------------------------------------------------

create table kml_job_assets (
  asset_id        number generated by default as identity
                     constraint kml_job_assets_pk primary key,
  job_id          number          not null,
  --- placement / grouping -----------------------------------------------------
  folder_name     varchar2(1000),                  -- optional <Folder> path; '/' nests
  display_order   number          default 0 not null,
  --- variable metadata (shown / stored on the feature) ------------------------
  name            varchar2(400),                   -- <Placemark><name>
  description     clob,                            -- <description> (HTML allowed, CDATA-wrapped)
  extended_data   clob,                            -- JSON object {"key":"value"} -> <ExtendedData>
  visibility      varchar2(1)     default 'Y' not null,
  --- geometry: supply EXACTLY ONE of the two ---------------------------------
  geometry_sdo    sdo_geometry,                    -- native Oracle geometry (preferred)
  geometry_geojson clob,                           -- GeoJSON geometry/feature (alternative)
  --- placement modifiers ------------------------------------------------------
  altitude_mode   varchar2(20),                    -- clampToGround | relativeToGround | absolute
  extrude         varchar2(1)     default 'N' not null,
  tessellate      varchar2(1)     default 'N' not null,
  --- style (KML colors are aabbggrr hex; see PCK_KML_ENGINE.rgba_to_kml) ------
  icon_href       varchar2(1000),
  icon_scale      number,
  label_color     varchar2(8),
  label_scale     number,
  line_color      varchar2(8),
  line_width      number,
  poly_color      varchar2(8),
  poly_fill       varchar2(1),
  poly_outline    varchar2(1),
  --- audit (auto-populated by PCK_KML_JOB_ASSETS_DML when passed NULL) --------
  created_at      timestamp       default systimestamp,
  created_by      varchar2(128)   default user,
  updated_at      timestamp       default systimestamp,
  updated_by      varchar2(128)   default user,
  constraint kml_job_assets_job_fk
    foreign key (job_id) references kml_jobs (job_id) on delete cascade,
  constraint kml_job_assets_visible_ck check (visibility in ('Y','N')),
  constraint kml_job_assets_extrude_ck check (extrude    in ('Y','N')),
  constraint kml_job_assets_tessel_ck  check (tessellate in ('Y','N')),
  constraint kml_job_assets_fill_ck    check (poly_fill    is null or poly_fill    in ('Y','N')),
  constraint kml_job_assets_outline_ck check (poly_outline is null or poly_outline in ('Y','N'))
)
lob (description)      store as securefile (enable storage in row)
lob (geometry_geojson) store as securefile (enable storage in row)
lob (extended_data)    store as securefile (enable storage in row);

create index kml_job_assets_job_ix
  on kml_job_assets (job_id, folder_name, display_order, asset_id);

comment on table  kml_job_assets                  is 'Generic map features for a job. The consuming app fills these; KMLeon renders them. DML only via PCK_KML_JOB_ASSETS_DML.';
comment on column kml_job_assets.folder_name      is 'Optional KML <Folder> path; ''/'' separates levels (e.g. Europe/Germany) for nested folders. NULL = directly under <Document>.';
comment on column kml_job_assets.geometry_sdo     is 'Native SDO_GEOMETRY (preferred). Converted to KML via SDO_UTIL.TO_KMLGEOMETRY.';
comment on column kml_job_assets.geometry_geojson is 'GeoJSON geometry/feature (used when geometry_sdo is NULL). Converted via SDO_UTIL.FROM_GEOJSON.';
comment on column kml_job_assets.extended_data    is 'JSON object of key/value pairs rendered as <ExtendedData> (visible in the feature balloon).';
comment on column kml_job_assets.line_color       is 'KML aabbggrr hex. Use PCK_KML_ENGINE.rgba_to_kml to convert from RRGGBB.';
comment on column kml_job_assets.poly_color       is 'KML aabbggrr hex fill color.';
