--------------------------------------------------------------------------------
-- KMLeon :: table KML_LOG
--------------------------------------------------------------------------------
-- Central application log. Written only by PCK_KML_LOG (which logs via an
-- autonomous transaction so entries survive a rollback of the calling unit).
--------------------------------------------------------------------------------

create table kml_log (
  log_id        number generated by default as identity
                   constraint kml_log_pk primary key,
  log_level     varchar2(10)  not null,            -- ERROR | WARN | INFO | DEBUG
  package_name  varchar2(128),
  routine_name  varchar2(128),
  job_id        number,                            -- optional correlation to KML_JOBS
  message       clob,
  --- audit (auto-populated by PCK_KML_LOG when passed NULL) -------------------
  created_at    timestamp     default systimestamp,
  created_by    varchar2(128)  default user,
  updated_at    timestamp     default systimestamp,
  updated_by    varchar2(128)  default user,
  constraint kml_log_level_ck check (log_level in ('ERROR','WARN','INFO','DEBUG'))
)
lob (message) store as securefile (enable storage in row);

create index kml_log_ts_ix  on kml_log (created_at);
create index kml_log_job_ix on kml_log (job_id);

comment on table  kml_log            is 'KMLeon central log. Written only by PCK_KML_LOG (autonomous transaction).';
comment on column kml_log.log_level  is 'ERROR | WARN | INFO | DEBUG.';
comment on column kml_log.job_id     is 'Optional correlation to KML_JOBS.job_id.';
